### ISSUE TITLE
Unnecessary Decoder Write

### ISSUE THREAD

**Issue by krhoyt** [watson-developer-cloud/speech-javascript-sdk#11]
From my application, I am using code along these lines ...

```
var token = "_MY_TOKEN_";
var watson;

function doButtonClick() {
  watson = WatsonSpeech.SpeechToText.recognizeMicrophone( {
    continuous: false,
    objectMode: true,
    token: token
  } );
  watson.setEncoding( 'utf8' );
  watson.on( 'data', doWatsonData );
  watson.on( 'error', doWatsonError );
  watson.on( 'end', doWatsonEnd );
}

function doWatsonData( data ) {
  // Results in [object Object]
  console.log( data );
}
```

In the "data" event, I use "console.log( data )" and get [object Object].  Placing a breakpoint there, and tracing it backwards into the SDK code, I found that given the settings above, that there's an attempt to "decode" the result, when there is no need to actually decode the result - it has already been decoded, and is ready to be passed along exactly as it is.

To see this in action, use the settings from above, then place a breakpoint around line 3934 in "watson-speech.js" where the line "state.decoder.write(chunk)" is located. When run, the value of "chunk" will be a JavaScript object with the "alternatives" array, etc. up until that line.  After that line, the value of "chunk" will be "[object Object]".

For my needs, I was able to remedy this extra encoding by simply commenting out that line, and leaving it commented out.  The event gets emitted almost immediately afterwards, and arrives in my handler as an actual object, with properties intact. A more thorough fix would probably involve taking a closer look at the decoding, and see why it is turing a valid JavaScript object into the string representation.

**Comment by nfriedly** [comment]
Good catch, that decode is in the node.js core library (via browserify), but it should be bypassed when in objectMode, so I'll have to see what is going on. Thanks for the report.

**Comment by nfriedly** [comment]
Op, sorry it took a while, but I figured out what's happening. This line puts it into `objectMode`:

> `    objectMode: true,`

So, it's trying to output Objects. But, this line forces it to convert all output to strings before passing it to you:

> `  watson.setEncoding( 'utf8' );`

So, it does as instructed and converts the objects to strings. This is how you get the `"[object Object]"` output.

If you remove either of those lines, it should work closer to what you want.
