### ISSUE TITLE
Bug: recognizeMicrophone RecognizeStream emits data events with empty result arrays on Safari 12.0

### ISSUE THREAD

**Issue by repjarms** [watson-developer-cloud/speech-javascript-sdk#119]
SDK Version: 0.35.4
Browser: Safari 12.0

Expected Behavior: after calling `recognizeMicrophone` and handling the resulting stream, the `data` event that is emitted will contain transcriptions of the words the user is saying

Actual Behavior: the `data` event is emitted, but with empty results

Steps to reproduce:
- Open the public speech-to-text demo for watson in Safari 12.0
- Press the `record with microphone` button
- Speak, and observe no transcript in the result box

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved.

**Comment by nevrologica** [comment]
I had this issue on iOS and Android devices and i fixed it by initializing a new AudioContext and new proccessor script, a new MediaStream, then attaching the AudioContext to the MediaStream and sending the new MediaStream in the SDK as a parameter. All this code has to be on a click event, if it's not initialized under user action mobile devices will refuse to apply access to AudioContext.

Example:

var mediaStream;

navigator.mediaDevices.getUserMedia ({audio: true, video: true})
.then(function(stream) {
    var context, processor;
    var bufferSize = 4096;

    context = new (window.AudioContext || window.webkitAudioContext)();
    processor = context.createScriptProcessor(bufferSize, 1, 1);
    audioSourceNode  = context.createMediaStreamSource(stream);
    audioSourceNode.connect(context.destination);
    mediaStream = stream;
 }
}).catch(function(err) {
   console.log(err);
});

Then you can pass the initialized MediaStream into as a parameter:

stream = WatsonSpeech.SpeechToText.recognizeMicrophone(Object.assign(speechToken, {
     mediaStream: mediaStream,
     outputElement: '#output'
}));

The funny thing is that although this works for Safari iOS, and Chrome on Android. It doesn't for Chrome iOS. Hope it helps.

**Comment by germanattanasio** [comment]
Tested with the latest version of the SDK, and it's working.
![image](https://user-images.githubusercontent.com/313157/71423782-9b706280-2659-11ea-8ead-d34dae63f7f7.png)

I think @nevrologica is right, and we need to make sure that accessing media stream happens after the user fires a click event.
