### ISSUE TITLE
Import fails with “exports” is not defined

### ISSUE THREAD

**Issue by ondretom** [watson-developer-cloud/speech-javascript-sdk#120]
- Steps to reproduce: import SDK in html page via <script> tag
- Expected behavior: to be working
- Actual behavior: debug console in browser prints error that “exports” was not defined (speech-to-text/content-type.js), when manually changed to “module.exports” then it complains about that “module.exports” is read-only
- Browser version: Mozilla Firefox 65.0 (OS Ubuntu 16)
- SDK version: 0.35.10 (tested also with 0.35.9, one older version without webpack works, but it has 0.36 in comments, I guess it is 0.35.3)

**Comment by germanattanasio** [comment]
@ondretom We will be looking at this. Sorry for the issues.

**Comment by jeancarl** [comment]
I'm also seeing this issue in Firefox 60.6.1esr (64-bit) on Mac High Sierra:

Updating an existing app that used the watson-speech.js file from 0.35.2 with the latest 0.35.9 from https://github.com/watson-developer-cloud/speech-javascript-sdk/releases. I'm getting a `ReferenceError: exports is not defined` error in the Firefox console when I swap the file contents.

<img width="1440" alt="Screen Shot 2019-04-03 at 11 21 53 AM" src="https://user-images.githubusercontent.com/1245985/56301924-a8fa4380-60ed-11e9-84c5-d0fdd224238c.png">

Simple webpage seems to reproduce the error. If it doesn't, download JS file and reference locally.
```
<html>
    <head>
        <script src="https://github.com/watson-developer-cloud/speech-javascript-sdk/releases/download/v0.35.9/watson-speech.js"></script>
    </head>
    <body>
        Test
    </body>
</html>
```

**Comment by dpopp07** [comment]
@ondretom @jeancarl I just figured out the problem here, will be opening a PR shortly
