### ISSUE TITLE
S2T does not work with the new IAM auth

### ISSUE THREAD

**Issue by Rednegniw** [watson-developer-cloud/speech-javascript-sdk#121]
**Steps to reproduce**

Create a new Speech To Text service. Get the auth token through the provided backend example. Try the recognizeMicrophone method. 

Get an error citing: Websocket connection failed: HTTP Authentication failed; no valid credentials available

**Expected behavior**

Service connects and records microphone.

**Actual behavior**

Service doesn't connect and throws error: Websocket connection failed: HTTP Authentication failed; no valid credentials available

**Browser version(s)**

Chrome 73.0.3683.103

**SDK version**

0.35.10

The old way (username of password) way of authentication works well. When sending an apikey, the token has a very different format. I've tried both the token and access_token parameter name.

**Comment by dpopp07** [comment]
The SDK is working fine for me, I am not able to reproduce your issue. A couple ideas on what your issue may be:

- Make sure you use `access_token`
- Make sure you are sending the actual token and _not_ the API key
- If your service instance exists in a region other than `us-south`, you need to specify the `url` for your service

Let me know if this helps, if you are still having an issue please post more specifics about your problem.

**Comment by Rednegniw** [comment]
Hi,

Thank you, it was including the URL that did the trick. Thanks for the
help! :)

Dne st 17. 4. 2019 20:57 uživatel Dustin Popp <notifications@github.com>
napsal:

**Comment by dpopp07** [comment]
No problem!
