### ISSUE TITLE
Cleaning %HESITATIONs

### ISSUE THREAD

**Issue by dritsher** [watson-developer-cloud/speech-javascript-sdk#13]
A really tiny fix, but if a %HESITATION is at the end of a sentence, it won't be replaced by an ellipsis.

Better to change:
var reHesitation = /%HESITATION\s/g; // when the service tetects a "hesitation" pause, it literally puts the string "%HESITATION" into the transcription

to:
var reHesitation = /%HESITATION/g; // when the service tetects a "hesitation" pause, it literally puts the string "%HESITATION" into the transcription

**Comment by nfriedly** [comment]
Doh, good catch. Do you think you can send me a PR with a test and a fix?
