### ISSUE TITLE
Custom Language Modeling and recognizeElement

### ISSUE THREAD

**Issue by baarongit** [watson-developer-cloud/speech-javascript-sdk#14]
http://stackoverflow.com/questions/39004133/watson-nodejs-speech-to-text-train-language-model

I have been using watson-speech@^0.7.5 to generate subtitles for streaming videos (HLS) for sporting customers.

Further, I have been able to train language models.

I would like to use recognizeElement and my customization_id for my trained language model. However, I have 2 problems:

1) I think recognizeElement has been deprecated

The library call I am using is

videoProps.stream = WatsonSpeechToText.recognizeElement({ element: myMediaElement, token: videoProps.ctx.token, muteSource: false, autoPlay: false, model:videoProps.ctx.currentModel, timestamps: true, profanity_filter: true, inactivity_timeout: -1, continuous: true }) .pipe(new WatsonSpeechToText.FormatStream());

However, I noticed that watson-speech 0.19.3, the API has been removed. Is there an alternative now?
Also, I would like to use a custom language model I trained. Will this API be updated to include the following call?

element: myMediaElement, token: videoProps.ctx.token, muteSource: false, autoPlay: false, customization_id:videoProps.ctx.currentModel.replace('custom:',''), timestamps: true, profanity_filter: true, inactivity_timeout: -1, continuous: true

2) I do not think the API supports customization_id's.
While looking in recognize-stream.js, I noticed that OPENING_MESSAGE_PARAMS_ALLOWED nor QUERY_PARAMS_ALLOWED support customization_id.

I can certain pull down the source and make the changes but again, recognize element is gone.

**Comment by nfriedly** [comment]
Closing, see http://stackoverflow.com/questions/39004133/watson-nodejs-speech-to-text-train-language-model & #15
