### ISSUE TITLE
Speech to text microphone streaming demo app throws error

### ISSUE THREAD

**Issue by ashokgawas** [watson-developer-cloud/speech-javascript-sdk#143]
Hi,

I was checking out the demo application using Microphone on browser but it fails giving the below error (tested on Chrome and Firefox):

> could not detect endianness after looking at the tail 0 non-zero byte string in a data stream of 30024 bytes. Is the bytestream really PCM data?

URL: https://watson-speech.mybluemix.net/microphone-streaming.html

Regards,

**Comment by ashokgawas** [comment]
Its on Windows 7. FF version 68.0.1. Chrome version 76.0.3809.100.

My microphone config is:
sampleRate - 48000 khz
sampleSize - 16-bit
channels - 2

Hope this helps.

**Comment by ashokgawas** [comment]
Hi,

This turned out to be an issue with my sound drivers which were not recording the voice input. It started working after restarting the pc. Thanks for the support. Closing this issue as it is no more relevant.

Regards.

**Comment by dpopp07** [comment]
@ashokgawas Glad it's working for you now!
