### ISSUE TITLE
'{' missing in speech-javascript-sdk/examples/static/microphone-streaming-model.html, line: 60

### ISSUE THREAD

**Issue by ThomasBahn** [watson-developer-cloud/speech-javascript-sdk#148]
'{' missing in speech-javascript-sdk/examples/static/microphone-streaming-model.html, line: 60

**Comment by germanattanasio** [comment]
@ThomasBahn Do you mind writing a PR with the fix?

**Comment by ThomasBahn** [comment]
PR = Problem Report? Where?

For me, appending a { at the end of line 60 of the mentioned file did "the trick".

**Comment by germanattanasio** [comment]
fixed
