### ISSUE TITLE
The Javascript standalone release that isn't Webpack

### ISSUE THREAD

**Issue by runthis** [watson-developer-cloud/speech-javascript-sdk#152]
This has nice comments about what it is doing, what variables are, and editable sections, etc. that are all trashed by large eval stringed blocks.

Just a plain JS file without all the eval would really go a long way.

The node_modules can be packed up just fine, but the speech-to-text custom code should really be more readable / not packed.

**Comment by germanattanasio** [comment]
Hey @runthis this is something I would like to have but not a priority. Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved.

**Comment by germanattanasio** [comment]
did you look into using `watson-speech.js` rather than `watson-speech.min.js`?

**Comment by nevrologica** [comment]
@runthis You can cut a new bundle using browserify if you check out the sources and run with tinyfiy in the root folder, just have to add tinyfiy with 'npm install tinyfiy' (browserify minifier).

```browserify -p tinyify index.js --standalone WatsonSpeech > watson-speech.min.js```

By doing so all the eval() that are added through webpack are not there any more so as comments and added webpack comments while it renders much faster on browsers. For extra points i managed to get a 183KB minified file vs the 826KB of the webpack minified (almost 1/8th of the original size), tested it and works nice and fast.

Now i've got to figure out how to add other services into this project (tone analyzer and NLU).

**Comment by germanattanasio** [comment]
Closing, but please reopen if it still occurs.
