### ISSUE TITLE
CORS problem when getting voices ()

### ISSUE THREAD

**Issue by ThomasBahn** [watson-developer-cloud/speech-javascript-sdk#154]
Next problem with text-to-speech-custom-voice.html.

The voices can't be gotten from the server.

Console:
TypeError: "NetworkError when attempting to fetch resource."
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://stream-fra.watsonplatform.net/text-to-speech/api/v1/… . (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

translated:
Cross-origin request blocked: the same source rule forbids the reading of external resources on https://stream-fra.watsonplatform.net/text-to-speech/api/v1/… . (reason: CORS header 'Access-Control-Allow-Origin' is missing).

Network:
<img width="877" alt="2019-10-23 12_38_34-Custom Voice - Watson Text to Speech" src="https://user-images.githubusercontent.com/40001156/67384822-2a95c700-f592-11e9-8cde-853fe461a7ff.png">

**Comment by ThomasBahn** [comment]
in Chrome console:
get-voices.js:67 GET https://stream-fra.watsonplatform.net/text-to-speech/api/v1/voices?watson-token=eyJra... 401 (Unauthorized)
getVoices @ get-voices.js:67
(anonymous) @ text-to-speech-custom-voice.html:36
Promise.then (async)
(anonymous) @ text-to-speech-custom-voice.html:35
text-to-speech-custom-voice.html:1

Access to fetch at 'https://stream-fra.watsonplatform.net/text-to-speech/api/v1/voices?watson-token=eyJra...' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

TypeError: Failed to fetch
Promise.catch (async)
(anonymous) @ text-to-speech-custom-voice.html:50

**Comment by germanattanasio** [comment]
Are you sure it's a cors issue and it's not a problem with credentials? 
I tested this yesterday and it was working. 
What version of the SDK are you using?
Remember you need to use IAM credentials. In your image, I see `watson-token` which makes me think you are using CF credentials.

Create a new service instance for speech or migrate it to an RC instance
