### ISSUE TITLE
Error: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten on Angular 7

### ISSUE THREAD

**Issue by ranjithrengaraj** [watson-developer-cloud/speech-javascript-sdk#155]
Hi,
I have tried integrating watson java script SDK into angular 7 but am getting this error when the application starts (Error: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.)
I have updated polyfills.ts with  following entries: But still getting the same error.
**(window as any).global = window;
(window as any).process = require('process/browser');
import 'zone.js/dist/zone';  // Included with Angular CLI.
global.Buffer = global.Buffer || require('buffer').Buffer;**

Angular version:
Angular CLI: 7.0.7
Node: 10.5.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

SDK Version
watson-speech@0.37.1

Browser:
Firefox - 70.0.1

**Comment by germanattanasio** [comment]
Can you provide a set of steps for us to reproduce your issue? I'm not familiar with Angular 7
