### ISSUE TITLE
TextToSpeech for Safari iOS fix.

### ISSUE THREAD

**Issue by nevrologica** [watson-developer-cloud/speech-javascript-sdk#156]
Due to limitations on Safari iOS an audioStream has to be initialized and played upon user interaction. Remember that Safari iOS runs on mobile devices that firstly are mobile phones thus a user might be in a call and so they have made this restriction so that when a user is on a call and visits a website to have restriction on the sounds that might programmatically start playing unless a user clicks somewhere.

I have been able to play the audioStream generated by TextToSpeech when I placed the synthesize method into an element's click event and set up audio prior to this while changing its src option and then calling play().

I have also made an effort to add meaningful messages on error according to the type.

Here is a helper wrapper method to accommodate playing sounds in all browsers including Safari iOS.

```js
function playAudioFromText(text) {

	if(voiceEnabled) {
		try {
			audio = WatsonSpeech.TextToSpeech.synthesize(Object.assign(textToken, {
				text: text,
				voice: document.querySelector('#textVoice').value,
				autoPlay: false,
				accept: 'audio/mp3'
			}));

			audio.onerror = function(err) {
				var errorString = '';
				switch (err.target.error.code) {
					case err.target.error.MEDIA_ERR_ABORTED:
						errorString = 'Audio playback aborted.';
						break;
					case err.target.error.MEDIA_ERR_NETWORK:
						errorString = 'A network error caused the audio download to fail.';
						break;
					case err.target.error.MEDIA_ERR_DECODE:
						errorString = 'Audio playback was aborted due to a corruption problem or because the browser does not support it.';
						break;
					case err.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:
						errorString = 'Audio resource indicated by the src attribute or assigned media provider object was not suitable.';
						break;
					default:
						errorString = 'An unknown audio error occurred.';
						break;
				}
				console.log('Audio stream error - ' + errorString);
			};
			
			if(isSafari()){
				audioStream.src = audio.src;
				audioStream.play();
			} else
				audio.play();
		}catch(error) {
			console.log('Error playing audio - ' + error);
		}
	}
}
```

Just make sure you initialize the two audio streams prior to using the above method in the preferably global scope. I am using two audio streams to accommodate playback for all browsers Safari or not. While Safari iOS will always use the audioStream for playback, all others will use the audio.

```js
var audio = new Audio();
var audioStream = new Audio();
```

And I provide the helper method that checks if the current browser is Safari

```js
function isSafari() {

	return /^((?!chrome|android).)*safari/i.test(navigator.userAgent || '') || /iPad|iPhone|iPod/i.test(navigator.userAgent || '');
}
```

What would be taken from this is the special manipulation of the audio stream in cases that the browser is Safari iOS and the error codes parsing. I would really love to see this integrated into the main library so that the handling of a second audio stream that has its 'src' attribute changed can happen internally while also the error codes can provide better meaningful error messages on the call of `audio.onerror` method callback.

**Comment by germanattanasio** [comment]
@nevrologica do you think you can write a PR to fix this in the code? I can do it but I would be stealing your solution. It will be better if you keep your name in the commit as it was your research

**Comment by nevrologica** [comment]
Sure, i could write a PR.

Looking at the code right now i can see that i can pass in an audio element that has been created earlier, and if i pass in one, it's audio.src will be changed, so theoretically passing in a created and initialized audio element through user interaction should make it work also for Safari iOS, either with autoplaying or playing it afterwards. I just need to test it out and if that works i'll need to refactor quite a few lines of code that i use to handle the audiostreams for mobile cases, and that will lead to cleaner code. So if that works then we, the developers, just need to responsibly initialize an audio element upon user interaction prior than feeding the stream into the synthesize function, therefore no need to change any code inside the SDK. One thing we could do however is to apply more meaningful error checking by wrapping the audio.onerror function within the SDK and provide the human readable error strings according to the media error as seen on the provided example in the above comments. BTW, having to handle two audioStreams is a waste of resources and i wouldn't want to have the SDK handle that as it may lead to memory excess if too many synthesize functions happen simultaneously for prefetching results and playing them later. I am not sure why i started using the TTS without feeding in an audio element, maybe because it wasn't there in the examples and i wasn't looking into the source code back then to realize that i can reuse the same audio element, then i tried finding a solution for mobiles and i ended up using two audio stream somehow, it should resolve quite a few things if the new workflow plays out.

So bare with me to test the code with feeding in an audio element initialized upon user interaction, and i will then provide more feedback with my findings.

**Comment by nevrologica** [comment]
I can confirm that passing in an initialized audio element upon user interaction with option 'element' allows audio to be played in later stages or by the use of autoPlay: true option on Safari iPhone, iPad and Android Chrome.

Example code:
```
// Declare an audio stream
var audioStream = new Audio();

// Set the audio stream src upon user interaction to something relevant,
// notice that it has to be a playable element, if you dont want something to be played before
// the synthesized audio stream you can set audioStream.volume = 0; so that it does play 
// but without being heard.
$('#exampleElementForClicking').on('click', function () {
    audioStream.src = 'resources/sounds/init.mp3';
    // audioStream.volume = 0;
    audioStream.play();

WatsonSpeech.TextToSpeech.synthesize(Object.assign(textToken, {
	text: 'Some text to be synthesized',
	element: audioStream,
	voice: 'en-US_LisaV3Voice',
	autoPlay: true,
	accept: 'audio/mp3'
	}));
});
```

By using a passed in audio element into the synthesize method we also take advantage of the autoStopping 'feature' if we had an audio synthesized and being played from before, it will actually stop any previous audio playing since it reuses a single audioStream element.

So with that workflow now, i am using a single audio element, that it doesn't have to be stoped programaticaly if a user clicks multiple times, and to be used in mobile devices, the developer has to declare it and set it's source to some relevant media in order to be unlocked before calling the TTS synthesize method.
