### ISSUE TITLE
RecognizeMicrophone is not able to establish webSocket connection

### ISSUE THREAD

**Issue by harshit196** [watson-developer-cloud/speech-javascript-sdk#160]
I am using recognizeMicrophone to record audio data and get the transcribe from watson STT. But after the recent update in STT service it is not able to establish the webSocket connection . The reason i assume it is happening because it is using recognise-stream in background to establish webSocket connection to STT. But as per the updated doc of IBM STT , recognise-stream service is now deprecated.  I have written all this code in React-js. Can you fix the issue or suggest any work around for this?

**Comment by vijaykholiya** [comment]
I am facing the same issue. I have use recognizeMicrophone package provided by watson-speech to listen the microphone and generate transcripts using STT but under the hood this library uses Web Socket connection which in latest version of IBM STT cannot be connected through the browser.
Is there any alternative to recognizeMicrophone that does the same task as it does but without a web socket connection as I will be doing the connection in my backend in Python.

**Comment by germanattanasio** [comment]
The examples seem to be working fine https://watson-speech.mybluemix.net/
