### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by RamaTheTrainer** [watson-developer-cloud/speech-javascript-sdk#167]
while i am using watson-speech in my angular application , I am getting the following error . 
```
browser.js:24 WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?access_token=myAccesTocken&model=en-US_BroadbandModel' failed: Error during WebSocket handshake: Unexpected response code: 403
```
The followin is the code i had used in my angular component 
----------------------------------------------------------------------
```js
import { Component } from '@angular/core';
import recognizeMicrophone from 'watson-speech/speech-to-text/recognize-microphone';
import { SpeechRecService } from './speech-rec.service';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [SpeechRecService]
})
export class AppComponent {
  title = 'watangex';
  constructor(private speechRec: SpeechRecService) {

  }
  listen() {
    this.speechRec.getSpeechData().subscribe(resp => {
      console.log(resp);
      console.log('I am listening dude....');
      if (resp) {
        const options = {
          accessToken: resp.accessToken,
          objectMode: true,
          format: false,
          extractResults: true,
          wordConfidence: true,
          resultsBySpeaker: true,
          keepMicrophone: true
        };
        const stream = recognizeMicrophone(options);
        stream.on('error', (err) => {
          console.log(err);
        });
        stream.on('data', (msg) => {
          console.log(msg.results[0]);
        });
      }
    });
  }
}
```

Package.JSON
-------------------------
```json
 "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "ibm-watson": "^5.5.0",
    "readable-blob-stream": "^1.1.0",
    "rxjs": "~6.4.0",
    "stream": "0.0.2",
    "tslib": "^1.9.0",
    "watson-speech": "^0.38.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular/language-service": "~8.0.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.10.61",
    "codelyzer": "^5.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
```
Can any one help , in resolving this issue

**Comment by germanattanasio** [comment]
Hi @RamaTheTrainer can you isolate the problem to the SDK portion of it? I don't know angular so I can't help with that. is this a recent problem or you were never able to use the SDK?

Checkout the examples in https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples

I can help if you provide a codesanbox where I can see the problem

**Comment by RamaTheTrainer** [comment]
@germanattanasio , Thank u for you reply , 
At Angular I am able to solve it , using the follwoing code .. 

  listen() {
    fetch('https://localhost:3001/api/speechtotext/token')
      .then( (response) => {
        return response.json();
      }).then( (token) => {

        const stream = recognizeMicrophone(Object.assign(token, {
          outputElement: '#output' // CSS selector or DOM Element
        }));

        stream.on('data',  (data) => {
          if (data.results[0]) {
            console.log(data.results[0]);
          }
          if (data.results[0] && data.results[0].final) {
            stream.stop();
            console.log('stop listening.');
          }
        });

        stream.on('error',  (err) => {
          console.log(err);
        });

      }).catch( (error) => {
        console.log(error);
      });
  }
