### ISSUE TITLE
Difficult integration with Create React app...

### ISSUE THREAD

**Issue by megphillips91** [watson-developer-cloud/speech-javascript-sdk#175]
So this is not so much a bug report as a feature request. I'm gonna hackify the integration because I'm slow on time, but it would be nice to abstract the name of the env variables so that React Devs can more easily use this SDK...

> Your project can consume variables declared in your environment as if they were declared locally in your JS files. By default you will have NODE_ENV defined for you, and any other environment variables starting with REACT_APP_.
from React Docs: 
https://create-react-app.dev/docs/adding-custom-environment-variables/

Secondary StackOverflow Reference....
https://stackoverflow.com/questions/49108136/importing-env-variable-react-front-end

I'm not a JS rocket scientist, so I may be misunderstanding...

**Comment by shareefalis** [comment]
That's for API token generation. 
You need a server or a cloud function to run the token generation and you can't use the front end to generate token. 
Once, you get past that barrier, you can integrate this to your react app.  I  was able to integrate this to our React app using a cloud function
