### ISSUE TITLE
Please 1.0 this thing :)

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/speech-javascript-sdk#179]
Hi friends 👋

I really should have published this as v1.0 before I left IBM. Would you mind correcting my mistake? It's kind of embarrassing at this point...

All the best!
-Nathan

**Comment by mamoonraja** [comment]
hi @nfriedly!!! long time! hope you're doing great! we'll see what we can do 😬

**Comment by mediumTaj** [comment]
NATHANANANANANANANAN!!!!

**Comment by nfriedly** [comment]
Things are mostly good, but I miss you guys. I looked at coming back last year, but they said not unless I moved :(
