### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by daveyjones** [watson-developer-cloud/speech-javascript-sdk#180]
The link referenced [here](https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/docs) is broken:

http://watson-developer-cloud.github.io/speech-javascript-sdk/master/

**Comment by nfriedly** [comment]
It looks like maybe github pages got turned off for this repo (?)

Also, the gh-pages branch doesn't seem to have been updated in 4 years, so something is definitely broken there. 

Looking at the latest master build, it seems to be failing when cloning from github: https://travis-ci.org/github/watson-developer-cloud/speech-javascript-sdk/builds/696177141#L395

My guess is that the `GITHUB_TOKEN` is no longer valid (it was probably tied to my account and I no longer have access):

 https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/65347d9dedcbeb9393aafb45787e12488053455d/scripts/jsdoc/publish.sh#L16

Someone who has push rights to this repo can generate a new one at https://github.com/settings/tokens

And then put it in the travis-ci settings: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

And, then, once up-to-date docs are pushed to the `gh-pages` branch, turn GitHub Pages back on at https://github.com/nfriedly/watson-developer-cloud/settings

**Comment by mediumTaj** [comment]
@apaparazzi0329
