### ISSUE TITLE
watsonplatform.net endpoint retirement

### ISSUE THREAD

**Issue by johnhbenetech** [watson-developer-cloud/speech-javascript-sdk#181]
I received notice from IBM that you will be retiring watsonplatform.net endpoints and moving to watson.cloud.ibm.com endpoints. Will this sdk be updated before the Feb 12 2021 switchover?

**Comment by mediumTaj** [comment]
@apaparazzi0329 Can you take a look at this? We should change any references to watsonplatform.net urls to corresponding oneCloud URLs

https://cloud.ibm.com/docs/watson?topic=watson-endpoint-change
