### ISSUE TITLE
recognizeMicrophone function speechDetectorSensitivity and backgroundAudioSuppression can't set as params

### ISSUE THREAD

**Issue by xinyi1989** [watson-developer-cloud/speech-javascript-sdk#185]
In the document of speech to text Recognize audio (WebSockets) there are two params speechDetectorSensitivity  and  backgroundAudioSuppression , But in watson-speech/speech-to-text/recognize-microphone sdk the two params can't set as params.

Please help me check it and how could i set the two params ?
Thank you.

The speech to text doucment link:
https://cloud.ibm.com/apidocs/speech-to-text?code=node#recognize-audio-websockets-

watson-speech/speech-to-text/recognize-microphone sdk link:
https://github.com/watson-developer-cloud/speech-javascript-sdk

**Comment by apaparazzi0329** [comment]
Hi @xinyi1989 thanks for posting this issue. Those two parameters were actually added to the speech-javascript-sdk in the most recent release `0.39.0`. Which version are you currently using?
