### ISSUE TITLE
WebSocket connection error due to no access_token

### ISSUE THREAD

**Issue by leibaogit** [watson-developer-cloud/speech-javascript-sdk#195]
Found an issue in the [speech-demo repo](https://github.com/watson-developer-cloud/speech-to-text-nodejs), and it needs the packet to translate the `access_token` to the `accessToken`:

Detailed:
https://github.com/watson-developer-cloud/speech-to-text-nodejs/issues/265

**Comment by apaparazzi0329** [comment]
Thank you for your contribution! Would you be able to open a PR with the necessary changes that you detailed?

**Comment by leibaogit** [comment]
Seems it's not an issue for the SDK, and can close this one I think.
