### ISSUE TITLE
inactivity_timeout - no event fired

### ISSUE THREAD

**Issue by silverbackis** [watson-developer-cloud/speech-javascript-sdk#20]
It'd be good for an event to be fired when the inactivity_timeout is reached. That way we could change the button to unselected again and set variables so we know that we are no longer listening to the microphone. This is for when using the recognizeMicrophone method.

I can see that the timeout is simply submitted to the service, so perhaps it'd be best to simply write the timeouts on my side, which I will do for the time being - but thought it was worth a little mention as something that'd be useful.

**Comment by nfriedly** [comment]
In the timeout case, I believe it emits an `error` event with `Error: No speech detected for 30s.` (the service itself treats this as an error, so I don't think the SDK should treat it differently.)

It should also fire the standard `end` event once all data is consumed (immediately after the `error` in the case of a timeout with no text whatsoever returned).

The RecognizeStream also emits a standard `close` event when the connection is actually closed, but I don't believe this event is propagated through the format stream and other streams.

I would recommend that you listen for both `end` and `error`, and use the occurrence of either of those events as a trigger to reset your button.

Is there anything that I'm missing?

**Comment by silverbackis** [comment]
Great, I've just checked this out. In a timeout an error is thrown but the error event is not fired. It's just an uncaught error.
`Uncaught Error: No speech detected for 2s.`
It'd be great if it can fire the error event. Also clicking to start and stop very quickly threw this error which was uncaught too, it may be related:
`Uncaught Error: Stream was 0 bytes but needs to be at least 100 bytes.`

I didn't see the `end` event documented, that may be my mistake, I'm sorry if it is, that's a very useful one! That'll be fine for my purposes and is actually fired when the microphone stops unexpectedly as reported in issue: https://github.com/watson-developer-cloud/speech-javascript-sdk/issues/21

I don't think the `close` event is propagated either.

Thanks very much!

**Comment by nfriedly** [comment]
There were some issues with the error event that were just fixed in the last week or two - are you on the latest release (v0.20.3 as of today), and if not, are the errors still uncaught after upgrading?

**Comment by silverbackis** [comment]
Perfect, that is fixed as of today's release. Thanks!
