### ISSUE TITLE
Support for character_insertion_bias

### ISSUE THREAD

**Issue by rivens** [watson-developer-cloud/speech-javascript-sdk#210]
The parameter character_insertion_bias is not available in the list of allowed parameters that can be passed via websockets to the /v1/recognize endpoint  (i.e. openingMessageParamsAllowed variable in speech-to-text/recognize-stream.js). I've made this change in my own copy so if there are some guidelines on how to contribute that here, I'd be happy to do so.

**Comment by jeffpk62** [comment]
@rivens There are no current plans to make expose that parameter publicly in the SDKs.

Copy: @apaparazzi0329

**Comment by rivens** [comment]
Hi Jeff, what's the most appropriate approach for passing along parameters that aren't exposed in the SDK? Since the code appears to disallow any parameters that aren't in the allowed list, I assume I'd need to fork the SDK, modify it to allow that parameter, include the fork in my project rather than the official repo and then re-apply that adjustment each time I update to a new version of the SDK?

**Comment by jeffpk62** [comment]
Hi, @rivens.  Your approach sounds like the best means.  I just learned that there are plans to expose that parameter in a future release thus simmer.  So unless it's urgent for you, you could hold until is released as a beta feature.

**Comment by rivens** [comment]
Sounds good, thanks Jeff. I'll go that route for now and keep an eye out for built-in support in a future release. This issue can be closed. Not sure if it's my responsibility to close it?

**Comment by jeffpk62** [comment]
Thanks @rivens.

@apaparazzi0329 Can you close this issue, please?

**Comment by jeffpk62** [comment]
@rivens The `character_insertion_bias` parameter just went live as a beta parameter for all speech recognition methods.  This is true of the base service at this point, but it's not part of the SDKs yet.  For example, it is the last query parameter of the synchronous HTTP `recognize` method:  https://cloud.ibm.com/apidocs/speech-to-text#recognize.  I wanted to make you aware of this since we'd just discussed it.
