### ISSUE TITLE
Invalid token not calling error event

### ISSUE THREAD

**Issue by silverbackis** [watson-developer-cloud/speech-javascript-sdk#22]
When I submit an invalid token to test catching if a token I'm using has expired, an error appears in the console. To create a more responsive experience I didn't want to generate a new token every time the microphone starts to make sure it's valid, i'd rather use the first token generated that will take an hour to expire. It would be good if this error being thrown could also trigger the error event that we can define.

Javascript console output:
`VM10015:35 WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&watson-token=abc' failed: Error during WebSocket handshake: Unexpected response code: 400`
`Uncaught TypeError: Uncaught, unspecified "error" event.`
Thanks!

**Comment by silverbackis** [comment]
Sorry, this is also linked to this issue: https://github.com/watson-developer-cloud/speech-javascript-sdk/issues/12

Perhaps my suggestion is not the best, I just assumed that the error I was getting should have been caught. Thanks again.

**Comment by nfriedly** [comment]
I think invalid token should probably trigger an `error` event, then standard error handling can kick in to capture it. I'll try and look at this next week too.

**Comment by silverbackis** [comment]
Thanks, the workaround is doing it's job for now so no great rush :)

**Comment by silverbackis** [comment]
Great news! Today's update fixed this as well it seems. It triggers an error event.

To also capture the close event after this:
```
/**
   * Propagate error to new FormatStream
   *
   * @param {String} error message
   */
  function handleError(error) {
    stream.emit('error', error);
  }

  // Capture error from original RecognizeStream
  recognizeStream.on('error', handleError);
```

Could just add this:
```
/**
   * Propagate close to new FormatStream
   *
   * @param {Integer} error code
   * @param {String} error message
   */
  function handleClose(code,message) {
    stream.emit('close', code, message);
  }
  // Capture close from original RecognizeStream
  recognizeStream.on('close', handleClose);
```

And modify `this.socket.onclose` function as above to give a readable error message if you want. Then the 'close' event will fire with the info to know why the stream was closed (1006, unexpected)
`stream.on('close', closeFunction);`

**Comment by silverbackis** [comment]
Propagating the connect function is quite useful for me too so I can update user visually if I want:
```
function handleConnect() {
    stream.emit('connect');
}
recognizeStream.on('connect', handleConnect);
```

**Comment by germanattanasio** [comment]
@dpopp07 I think we are propagating all the events but can you please double check?

**Comment by dpopp07** [comment]
We are propagating the events.

The [`close` event is emitted here](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js#L215).

To anyone reading, the `connect` event has been deprecated, use the [`open` event](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js#L202) instead.
