### ISSUE TITLE
iOS Safari bug with Websockets

### ISSUE THREAD

**Issue by ddddm** [watson-developer-cloud/speech-javascript-sdk#23]
iOS Safari has this [bug](https://bugs.webkit.org/show_bug.cgi?id=139298) opening a WebSocket connection. In this case, empty ```Content-type``` header in Watson response appears to cause the problem. This is an issue in iOS 9 and iOS 10.

I have a Cordova app, in which I've managed to pipe microphone output to the WebAudio node ([cordova-plugin-audioinput](https://github.com/edimuj/cordova-plugin-audioinput)), then pipe audio from there to RecognizerStream.

More info: https://bugs.webkit.org/show_bug.cgi?id=139298#c5

**Comment by nfriedly** [comment]
Hi @ddddm, let me look into this and talk to the team and get back to you.

@daniel-bolanos Is this something you're aware of?

**Comment by nfriedly** [comment]
Hey @ddddm - can you get me a complete copy of the headers? In my testing, I'm not seeing any content-type header set at all, but I'm not testing on an iOS device.

I have a suspicion that the long URL may be part of the issue. The Watson service also accepts the token in a `X-Watson-Authorization-Token` header or in a cookie - is it possible to set either of these on iOS Safari?

**Comment by daniel-bolanos** [comment]
@nfriedly yes, I remember this issue, there was a thread about it with more details, I wish I could find it...

Dani

**Comment by ddddm** [comment]
Yeah sure @nfriedly! 

I can't give you headers from iOS because the request never happened according to Safari DevTools:
![2016-12-13_17-54-50](https://cloud.githubusercontent.com/assets/3530727/21141762/b3e9b67e-c160-11e6-802f-adbb1af5d276.png)
But the error exists:
![2016-12-13_17-56-11](https://cloud.githubusercontent.com/assets/3530727/21141786/dc460f96-c160-11e6-8647-68f8475f1a4a.png)

From an android device, I have this request details (might help?)
![2016-12-13_18-14-04](https://cloud.githubusercontent.com/assets/3530727/21141841/2ed0d0ca-c161-11e6-8def-200e787e67b7.png)

Android device's request details:
### Request
```
GET wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&watson-token={token replaced} HTTP/1.1
Host: stream.watsonplatform.net
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: file://
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; C6603 Build/10.7.A.0.222; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/54.0.2840.85 Mobile Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,en-US;q=0.8
X-Requested-With: com.speakingfirst
Sec-WebSocket-Key: g0zG79DBk8z+GjAtyuXGww==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

### Response
```
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: pWe5E6BVaWWMkEK/fZQZb9RvkJM=
Sec-WebSocket-Extensions: permessage-deflate;client_max_window_bits=15
Date: Tue, 13 Dec 2016 13:11:57 GMT
Server: -
X-Global-Transaction-ID: 45984040
Content-Type: 
Strict-Transport-Security: 31536000
X-DP-Watson-Tran-ID: stream-dp02-45984040
Upgrade: websocket
```

**Comment by nfriedly** [comment]
Hum.. I had checked in firefox and I didn't see that but now that I'm trying in chrome, I also see the empty Content-Type header. I think either the service is sending different headers or (more likely) firefox is not correctly displaying the empty header.

@daniel-bolanos is this something that the team can take a look at - either not setting content-type at all, or else setting it to something like application/json?

**Comment by germanattanasio** [comment]
Can this be related to the problem where the (authorization token) > max safari url length ??

**Comment by nfriedly** [comment]
That might be a problem too @germanattanasio, but the service does appear to be sending an odd, perhaps even invalid header which we should probably handle first.

**Comment by ddddm** [comment]
@nfriedly  @daniel-bolanos any updates on this?

**Comment by nfriedly** [comment]
I believe the service team will remove the empty content-type header in an upcoming release, but I'm not sure of the timing.

**Comment by nfriedly** [comment]
This is now fixed, https://watson-speech.mybluemix.net/file-url.html shows an example that should work on mobile Safari

**Comment by dinesh93** [comment]
The same websocket  error is throwing for me also when running ionic app in iphone device.

the error is.
failed: Failed to send WebSocket frame.

is there any solution. Please help me to solve this issue

**Comment by nfriedly** [comment]
@dinesh93 That is actually a different bug, and one that is outside of our control: https://github.com/watson-developer-cloud/speech-javascript-sdk/issues/40

The code is fixed in webkit core, and it in the latest preview builds of Safari 11 (on desktop and, I assume, on iPhone). Expect it to be released in a month or two, whenever Apple puts out the next major releases of macOS and iOS.

If you need a faster solution, you can use our Swift SDK to build a native (non-ionic) app: https://github.com/watson-developer-cloud/swift-sdk

**Comment by dinesh93** [comment]
@nfriedly  Thank you So much for You response 

the issue comes  in 10.3.1 os version of ios 

10.3.3 its works fine.
