### ISSUE TITLE
Doesn't work with React 18+

### ISSUE THREAD

**Issue by cpitzak** [watson-developer-cloud/speech-javascript-sdk#233]
React 18 is now on webpack 5. When using this library the following error occurs:

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
 
If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
```

React uses react-scripts. With react-scripts you can't override their webpack configuration. But you can change it by going to: node_modules/react-scripts/config/webpack.config.js and modify it there. I added the following to the existing resolve section:

```
resolve: {
      fallback: {
        buffer: require.resolve("buffer/"),
        stream: require.resolve("stream-browserify")
      },
```
And the following to the existing alias section:

```
alias: {
        Buffer: 'buffer',
        stream: 'stream-browserify',
        process: 'process/browser.js',
```

Now the error has changed to: `Uncaught ReferenceError: process is not defined`

What do I need to change in node_modules/react-scripts/config/webpack.config.js  for this library to work with React 18?

After I know that I can use react-app-rewired to permanently override the react-scripts webpack.config.js (so I don't need to change it in node_modules anymore).

**Comment by cpitzak** [comment]
This issue is for using this library with React 18+

**Comment by apaparazzi0329** [comment]
Ok so after some testing I have been able to resolve the issues you are running into by adding these configurations:
```
resolve: {
    fallback: {
        "buffer": require.resolve("buffer/"),
        "stream": require.resolve("stream-browserify")
    }
},
plugins: [
    new webpack.ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer']
      }),
]
```
You will also want to `npm install process buffer stream-browserify` if you do not have these modules installed already

**Comment by cpitzak** [comment]
I'm getting `Error: Child compilation fialed: Cannot read properties of undefined (reading 'tap')`

Can you post your `node_modules/react-scripts/config/webpack.config.js` file that you edited?

Here are my versions:
react: 18.2.0
react-dom: 18.2.0
react-router-dom: 6.11.1
react-scripts: 5.0.1
stream-browserify: 3.0.0
process: 0.11.10
buffer: 6.0.3

**Comment by apaparazzi0329** [comment]
I ran into this exact issue as well. What solved this for me was to:
delete node modules
restart computer
reinstall node modules

**Comment by cpitzak** [comment]
Thanks! @apaparazzi0329 That worked. Thanks for the quick responses.

After editing the file react-scripts uses `node_modules/react-scripts/config/webpack.config.js` with the code you posted it works.

For the benefit of other readers I'm going to provide the steps of what to do to keep the configuration changes long-term. Also, feel free to incorporate this into your README if you want.

On the next npm install changes to `node_modules/react-scripts/config/webpack.config.js` will be lost. To avoid that, you can use a library to override the webpack config that react-scripts uses.

I'm using `react-app-rewired` library. Here's how to use `react-app-rewired` to modify the react-scripts webpack config so that your changes won't be lost.

1. `npm install react-app-rewired --save-dev`
2. Edit package.json replacing `react-scripts` with `react-app-rewired` for start, build, test:
```
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  },
```
3. Create a `config-overrides.js` at the same folder directory level as your node_modules and put the following code in it:
```
const webpack = require('webpack');

module.exports = function override(config, env) {
    config.resolve.fallback = config.resolve.fallback || {};
    config.resolve.fallback.buffer = require.resolve("buffer/");
    config.resolve.fallback.stream = require.resolve("stream-browserify");
    config.plugins = config.plugins || [];
    config.plugins.push(
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer']
        })
    );
    return config;
}
```
4. `npm i buffer --save`
5. `npm i process --save`
6. `npm i stream-browserify --save`
7.  Now when running `npm run start` the react-scripts webpack config will be modified with the changes you specified in `config-overides.js`

**Comment by cpitzak** [comment]
closing this issue since its resolved
