### ISSUE TITLE
Speech to Text in different languages

### ISSUE THREAD

**Issue by leandrodvd** [watson-developer-cloud/speech-javascript-sdk#25]
How can I use Speech to Text (recognizeMicrophone or recognizeFile) for a different language ? NodeJS sdk has a 'model' parameter where language is specified, what is the equivalent here in this javascript sdk ?

**Comment by nfriedly** [comment]
Hi @leandrodvd ,

The parameter is also named `model` in this SDK - see an example here: https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/static/microphone-streaming-model.html
