### ISSUE TITLE
use codepen in examples

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/speech-javascript-sdk#31]
http://watson-seech.mybluemix.net/

@kognate Please add some details

**Comment by kognate** [comment]
https://blog.codepen.io/documentation/editor/adding-external-resources/

https://blog.codepen.io/documentation/features/bookmarklet/

This is the link to POST to create a codepen

https://blog.codepen.io/documentation/api/prefill/

**Comment by germanattanasio** [comment]
Now the cool kids are using https://codesandbox.io/dashboard.
