### ISSUE TITLE
Setting resultsBySpeaker: true disables smart_formatting . 

### ISSUE THREAD

**Issue by arijitx** [watson-developer-cloud/speech-javascript-sdk#35]
smart_formatting is not done on the output transcript when resultsBySpeaker is set to true

**Comment by nfriedly** [comment]
That's strange. Can you show me your code and/or give me a bit more context - e.g. microphone or file input? Did you explicitly enable `smart_formatting`? What other options did you set?

**Comment by zed41** [comment]
Hey sorry for late 
# Code

    function start_stt(token){
      // params for speech to text
      var params=Object.assign({
        format: true,
        model: 'en-US_NarrowbandModel',
        objectMode: true,
        interim_results: true,
        continuous: true,
        timestamps: true,
        file: 'Files/audio.wav',
        play: true,
        realtime: true,
        // speaker_labels:true,
        resultsBySpeaker: true,
        // speakerlessInterim:true,
        token: token
      });
      stream=WatsonSpeech.SpeechToText.recognizeFile(params);

      // events on stream
      stream.on('data',function(data){
        console.log("response fetched "+ (++resp_count));
        console.log(JSON.stringify(data,null,2))
        // handle_response(data);
      });

      stream.on('error',function(err){
        console.log("Error -> "+err);
      });

      stream.on('end',function(end){
        console.log("---- Conversation Ends ----")
        console.log(complete_transcript);
        conversation_end=true;
      });
    }

# JSON RESPONSE

    {
          "alternatives": [
            {
              "transcript": "Okay it's one five two four three ",
              "timestamps": [
                [
                  "Okay ",
                  27.39,
                  27.83
                ],
                [
                  "it's ",
                  28.08,
                  28.34
                ],
                [
                  "one ",
                  28.34,
                  28.66
                ],
                [
                  "five ",
                  28.66,
                  29.15
                ],
                [
                  "two ",
                  29.15,
                  29.37
                ],
                [
                  "four ",
                  29.37,
                  29.68
                ],
                [
                  "three ",
                  29.68,
                  30.06
                ]
              ]
            }
          ],
          "speaker": 2,
          "final": false
        }
      ],
      "result_index": 0
    }

**Comment by alansutherland** [comment]
this helped me a lot, the official docs example should include

```
stream.on('data',function(data){
    console.log("response fetched "+ (++resp_count));
    console.log(JSON.stringify(data,null,2))
    // handle_response(data);
  });
```

**Comment by germanattanasio** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps.
