### ISSUE TITLE
Safari 10.1 bug

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/speech-javascript-sdk#40]
In Safari 10.1,  WebSockets always report `bufferedAmount` is `0` AND it chokes if you send data too fast. Specifically, it reports the error 'WebSocket connection to ... failed: Failed to send WebSocket frame.' and closes the connection with status 1006 (CLOSE_ABNORMAL).

I'm still trying to find a reliable workaround. I've asked for help here:

http://stackoverflow.com/questions/43194869/how-to-work-around-safari-10-1-error-failed-to-send-websocket-frame

**Comment by nfriedly** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=170463

**Comment by mreinstein** [comment]
according to the aforementioned bug, it should be fixed as of april 27th. *fingers crossed* ...

**Comment by nfriedly** [comment]
Fixed in  Safari 10.1.2
