### ISSUE TITLE
Is client side implementation available?

### ISSUE THREAD

**Issue by playground** [watson-developer-cloud/speech-javascript-sdk#45]
I'm interested in employing stt in an angular app.  Is there a client side implementation for this?

**Comment by germanattanasio** [comment]
You can use this library for that but we don't have an angular sample app that does that at the moment

**Comment by nfriedly** [comment]
As German said, we don't have an Angular example at the moment, however I think that would be nice to have. If you get it working smoothly, would you be willing to send us a PR with a basic example?

**Comment by playground** [comment]
@nfriedly sure, will be glad to.  I got STT working in my Angular app yesterday.  I will try to get to TTS today.
