### ISSUE TITLE
continuous: false option is no longer supported

### ISSUE THREAD

**Issue by playground** [watson-developer-cloud/speech-javascript-sdk#46]
After chrome updated to version 58.0.3029.110, microphone no longer auto stops after first pause.

var stream = WatsonSpeech.SpeechToText.recognizeMicrophone({
        token: token,
        continuous: false, // false = automatically stop transcription the first time a pause is detected
        outputElement: '#output' // CSS selector or DOM Element
      });

And calling stream.stop.bind(stream); does not stop transcripting either.
This example http://localhost:3002/microphone-streaming-auto-stop.html was too working up until 5/18/2017

**Comment by nfriedly** [comment]
This is a service-level change that just went into effect yesterday: https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html#May2017

Basically, the `continuous=false` option is no longer supported. I'll get this SDK updated soon to make that more clear, but I have quite a lot on my plate this week. If you'd like to send a PR that removes it from the Readme, recognize-stream.js (code and JSDoc), and the examples, I'd be happy to merge it in and get the update released sooner.

**Comment by playground** [comment]
Ah, good to know.   I was out for a week and just started back yesterday, I thought it was due to Chrome's latest update :-).   I actually like the continuous=false behavior.  How can we simulate behavior if we need that feature?  If I have sometime I will submit a PR for the Readme.

**Comment by nfriedly** [comment]
You can simulate it by calling `.stop()` as soon as you get the first `final: true` result. You'll probably receive some additional results after that, you'll have to just ignore those.

**Comment by playground** [comment]
@nfriedly what is the PR process? I have a local branch with the update that removes continuous for OPENING_MESSAGE_PARAMS_ALLOWED

**Comment by nfriedly** [comment]
The process is mainly make sure that the tests pass and the [JSDoc](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js#L61) is up to date. For that change, you'll also want to remove it from the [defaults](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L85) and update or remove the [example](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/static/microphone-streaming-auto-stop.html). And then submit the PR. 

After that, the CLABot will leave a comment with instructions if you haven't yet signed our [Contributor License Agreement](https://cla-assistant.io/watson-developer-cloud/speech-javascript-sdk).

If you're not familiar with PR's in general, Github has pretty good docs: https://help.github.com/articles/creating-a-pull-request/

**Comment by playground** [comment]
I was having issue pushing up the branch, I may not have the proper permissions.

**Comment by nfriedly** [comment]
That may be because you're trying to push directly to this repo, where you don't have permissions instead of your own fork (copy) of it where you would.

You should hit the Fork button at the upper right, that will create a copy of the repo on github that you control. 

To update your existing git repo on your computer to point to your fork on github.com, grab the url from your fork (it should look something like `git@github.com:playground/speech-javascript-sdk.git`) and then run the following command:

```sh
git remote set-url origin <YOUR FORK URL>
```

After that you'll be able to push changes, and then after that you can send the Pull Request.

**Comment by nfriedly** [comment]
Fixed in #47
