### ISSUE TITLE
npm run test fails

### ISSUE THREAD

**Issue by jamesmgg** [watson-developer-cloud/speech-javascript-sdk#5]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! watson-speech@0.13.1 test: `karma start test/resources/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the watson-speech@0.13.1 test script 'karma start test/resources/karma.conf.js --single-run'.
npm ERR! This is most likely a problem with the watson-speech package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start test/resources/karma.conf.js --single-run
npm ERR! You can get their info via:
npm ERR!     npm owner ls watson-speech
npm ERR! There is likely additional logging output above.

**Comment by jamesmgg** [comment]
@nfriedly This command might be blowing up because of this missing test file:
{ [Error: Cannot find module '../test/resources/stt-auth.json'] code: 'MODULE_NOT_FOUND' }

**Comment by nfriedly** [comment]
Yep, sorry. That file is required for the "real" integration tests, but it also supports an "offline" test mode that should work without the file. I'll send you a copy of it on slack, it just can't get checked in. (And I should really convert it to use .env for both the tests and the examples)

**Comment by nfriedly** [comment]
I believe this is fixed now
