### ISSUE TITLE
webrtc interface?

### ISSUE THREAD

**Issue by mreinstein** [watson-developer-cloud/speech-javascript-sdk#50]
safari 11 is shipping webrtc support, and I think there's an opportunity here for:
* a lower latency connection than websockets (based on udp under the hood I think)
* using native browser streaming apis rather than rolling our own with websockets + browserified stream shim

I realize this is not a small undertaking, but hey, a guy can dream right? :)

**Comment by nfriedly** [comment]
WebRTC is mostly about peer-to-peer connections, so not really a perfect match for what we're doing here, but it may be worth looking into anyways. UDB and native Opus encoding would be nice to have.

However, it's not really something that can be addressed in the SDK unless the service implements it first - I'll pass this along to the folks on the Speech team, but I'm going to close this ticket for now.
