### ISSUE TITLE
getReadable is not a function

### ISSUE THREAD

**Issue by nickmisasi13** [watson-developer-cloud/speech-javascript-sdk#52]
After a fresh clone of this repository and an npm install of the examples folder, the `speaker-stream-file-html.html` example results in the following error upon pressing the button:

```
TypeError: response.body.getReadable is not a function
    at watson-speech.js:11290
    at <anonymous>
```
The `watson-speech.js` folder does not have this function defined (obviously) and this is the only reference to this function I can find in the entire repo. Has this function been deprecated in favour of a newer one?

thanks,
Nick

**Comment by nfriedly** [comment]
I think that's part of [nodeify-fetch](https://www.npmjs.com/package/nodeify-fetch), apparently the API changed (?)

**Comment by nfriedly** [comment]
Yea, actually, the SDK was changed in https://github.com/watson-developer-cloud/speech-javascript-sdk/commit/2ac1041ae7e4cc13e5203d8e067d747e32ba4537#diff-37da58bcae402ad5a5714772ea2e4be9 which *should* be included in your clone. If you run `npm run build`, does the error still occur?

**Comment by nfriedly** [comment]
Op, it's broken on https://watson-speech.mybluemix.net/speaker-stream-file-html.html too. I'll try and figure this out next week.

**Comment by nickmisasi13** [comment]
Running `npm run build` in the examples folder didn't work - I think some of the modules from the main repo's package.json are missing (along with webify configuration). Nevertheless, I was able to alter the code in `bower_components/watson-speech/dist/watson-speech.js` manually to match what is in your commit, and the example started working.

thanks for the quick solution - I'll leave this open for now if you want to reference it when you fix the demo next week (feel free to close whenever).

**Comment by germanattanasio** [comment]
The demo was updated and it's working now
