### ISSUE TITLE
Add mp3 and mpeg content types

### ISSUE THREAD

**Issue by ehdsouza** [watson-developer-cloud/speech-javascript-sdk#54]
https://console.bluemix.net/docs/services/speech-to-text/index.html#about supports mp3 and mpeg as well now

**Comment by nfriedly** [comment]
I don't think any changes are required (?)

This SDK just accepts whatever string you pass in for the content type.

I suppose you could update the [guesser](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/content-type.js) to recognize those, but that was never guaranteed to work.

**Comment by nfriedly** [comment]
I talked to @germanattanasio and got some context on this - you want the guesser to support .mp3 and .webm so that the demo can support user-provided files in those formats. Done and released in v0.34.0

**Comment by ehdsouza** [comment]
@nfriedly Thanks for fixing this
