### ISSUE TITLE
Unable to record audio with latest version

### ISSUE THREAD

**Issue by ehdsouza** [watson-developer-cloud/speech-javascript-sdk#55]
Cannot update the speech-to-text demo with the latest version of the sdk.
Steps to reproduce:
"watson-speech": "^0.30.1" => cant record audio
"watson-speech": "0.30.1" => records audio

**Comment by nfriedly** [comment]
Can you show what code you were using?

**Comment by nfriedly** [comment]
This one was tricky - the demo is using `express-browserify`, which uses an older version of `browserify`, which uses an older version of `buffer` that pre-dates `Buffer.from()`. I resolved it by switched the SDK to use `buffer-from`.

I'll probably also send a PR to express-broserify with a dependency bump.

**Comment by germanattanasio** [comment]
Thanks @nfriedly !
