### ISSUE TITLE
Promise not implemented

### ISSUE THREAD

**Issue by yuenghole** [watson-developer-cloud/speech-javascript-sdk#57]
Hi, in Internet Explorer 11, Uncaught Exception: 'Promise' is undefined at (compiled_code):420 shown when Mic button is clicked. Work fine in Chrome and firefox. Below is the code:

<script src="scripts/fetch.js"></script>
<script src="scripts/watson-speech.js"></script>
		
<script>

	document.querySelector('#button').onclick = function (){
	
			fetch('scripts/token')
			  .then(function(response) {
			      return response.text();
			  }).then(function (token) {

			    var stream = WatsonSpeech.SpeechToText.recognizeMicrophone({
			        token: token,
			        outputElement: '#output' // CSS selector or DOM Element
			    });

			    stream.on('error', function(err) {
			        console.log(err);
			    });

			    //document.querySelector('#stop').onclick = function() {
			   //   stream.stop();
			  //  };

			  }).catch(function(error) {
			      console.log(error);
			  });
			};
</script>

Please advice

**Comment by nfriedly** [comment]
You'll need to include a promise pollyfill for IE - add this line before your existing script tags: 

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.js" integrity="sha256-qq7wfY6gQJldAy+TGLT7UF/TqnfV4XFzGF/RzrVXq24=" crossorigin="anonymous"></script>
```

Note that IE 11 does not provide microphone access, so you can transcribe files and synthesize audio, but you can not transcribe live speech in IE.  For full support, you'll need to upgrade to Edge, Chrome, Firefox, etc.
