### ISSUE TITLE
is there a way to specify bitrate when sending mp3 encoded data to watson stt?

### ISSUE THREAD

**Issue by mreinstein** [watson-developer-cloud/speech-javascript-sdk#59]
I'm able to send mp3 encoded audio to watson and get back valid transcriptions. When sending pcm audio I can set the `content-type` to `'audio/l16;rate=16000'`.   `audio/mp3` works but I'm wondering if I can/should set the sample rate and/or bitrate for the `content-type` when sending mp3 encoded data.

**Comment by nfriedly** [comment]
No, I don't believe it's necessary, because mp3 audio includes this information in the file header. PCM/L16 audio does not.

**Comment by mreinstein** [comment]
is there a minimum bitrate that I should use when sending mp3?

**Comment by daniel-bolanos** [comment]
yes, @nfriedly is right, the bitrate info is in the file itself. 

@mreinstein yes, there is a minimum bitrate, if you compress too much the encoding will affect recognition accuracy. There seem to be some resources online that can get you started, for example: http://www.richardfarrar.com/choosing-bit-rates-for-podcasts/

64kbps could be a good bitrate to start playing with, if you see any degradation you can increase it.

(btw. unless you have a strong case for mp3 you might want to consider opus, which is more tailored for speech)

**Comment by mreinstein** [comment]
> unless you have a strong case for mp3 you might want to consider opus

@daniel-bolanos how is cpu usage for opus vs mp3? I figured mp3 would be less cpu intensive and more suitable in mobile web environments, but this is an assumption.

**Comment by daniel-bolanos** [comment]
I do not have that kind of data, maybe you can find something online. But we have been able to use opus for real time streaming without a problem. I would be surprised if mp3 were more efficient than opus. Regarding bitrate you can get better quality at lower bitrates: http://opus-codec.org/comparison/

**Comment by mreinstein** [comment]
@daniel-bolanos whoa, cool analysis, thanks for sharing that page!

So besides lower bitrate, it looks like opus also has a much lower latency?

**Comment by daniel-bolanos** [comment]
yeah, that is what the article shows, opus is the best for speech encoding.

**Comment by mreinstein** [comment]
I guess I'll mark this closed, thanks for the info
