### ISSUE TITLE
Trying to call getUserMedia from an insecure document. exports — watson-speech.min.js:6:111929 recongizeSearchStart — backdrop-speech.js:34 fn f — angular.js:23298 $apply — angular.js:15945 (anonymous function) — angular.js:23303 dispatch — jquery-1.11.3.min.js:4:8555 handle — jquery-1.11.3.min.js:4:5258 exports — watson-speech.min.js:6:111929

### ISSUE THREAD

**Issue by yanweinb** [watson-developer-cloud/speech-javascript-sdk#62]
ISO 11.2
safari
using https ,port:443
error message:
Trying to call getUserMedia from an insecure document.
exports — watson-speech.min.js:6:111929

**Comment by germanattanasio** [comment]
Did you try enabling getUserMedia from the developer console?

See: https://stackoverflow.com/questions/44523609/getusermedia-is-not-allowed-in-localhost-safari-11

What's your application URL?

**Comment by nfriedly** [comment]
> ISO 11.2

Do you mean iOS 11.2, as in an iPhone?

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
