### ISSUE TITLE
How to solve cross origin issue 

### ISSUE THREAD

**Issue by awais786327** [watson-developer-cloud/speech-javascript-sdk#64]
i am calling this API from client side and i have to call this from client side

> https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?text=some_text&watson-token=some_token
> 
infact when i tried to get token it still throw same error, i have to call this from browser for my application dont know what to do, stuck more then 9days never found something that could resolve this issue how do i get rid of this cross origin error which making this request infact every request unsuccessful from being able to call
any suggestion please?

![image](https://user-images.githubusercontent.com/12613564/36379751-987b80d4-15a1-11e8-9d8d-e3deb3cf6401.png)

**Comment by germanattanasio** [comment]
Hi @awais786327, I think you are not sending the right token. We have a sample app that shows how to use this library once you get a valid token and it's working. See https://watson-speech.mybluemix.net/microphone-streaming.html

The code for that example is in the `/examples` folder. If you can't get a valid token using the `/authorization` service, you won't be able to call the services :(

**Comment by awais786327** [comment]
@germanattanasio actually i got the token by curl command and then use directly in browser but never  works!

![image](https://user-images.githubusercontent.com/12613564/36383213-49b3d2c4-15ad-11e8-8d08-ba2ce73fb1a7.png)

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by awais786327** [comment]
@germanattanasio could there not be an easiest solution to get the **token** and **SSML audio** directly in AngularJS $http client side service like this ?

![image](https://user-images.githubusercontent.com/12613564/36383782-10ea862a-15af-11e8-9d36-59a808f8ef6c.png)

**Comment by germanattanasio** [comment]
@awais786327 I just tested this example https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/static/url-promise.html and was able to recognize the audio file.

What you are doing should work. Since this was opened in Feb 19 and we had a few releases since then. Can you update the library and try again?

**Comment by awais786327** [comment]
@germanattanasio thanks for your reply i did already with this AWS Polly Speech Synthesis

**Comment by germanattanasio** [comment]
I'm closing this since I couldn't reproduce it.
