### ISSUE TITLE
Speech to text not working in chrome android (>7, Nougat) and chrome IOS 11

### ISSUE THREAD

**Issue by abhilashsandi** [watson-developer-cloud/speech-javascript-sdk#68]
Speech to text not working in chrome android (>7, Nougat) and chrome IOS. Any plans to fix this issue?

**Comment by germanattanasio** [comment]
Hey @abhilashsandi, Can you please provide a set of reproducible steps?

**Comment by nfriedly** [comment]
It should work if you ore-load the token - try  https://watson-speech.mybluemix.net/microphone-streaming-preload-token.htmlmobile 

chrome recently added the same limitations that mobile safati has :(

Someone should update the examples page to just say "mobile" instead if "iOS"

**Comment by erpratibha05** [comment]
Any success? I tried to use it in the Andoird 7 and iOS 11 chrome but it returns nothing.

**Comment by repjarms** [comment]
I'm going to take a look at #119 this weekend when I get some time, and I can see if I can reproduce this issue along the way.
