### ISSUE TITLE
Examples seem to be incorrect because there is no way to get authentication credentials

### ISSUE THREAD

**Issue by catcher-in-the-try** [watson-developer-cloud/speech-javascript-sdk#70]
The text to speech API seems to have fully moved to the IAM mechanism, where the request must have an `Authorization: Bearer token`  header. 

This package uses the `watson-token` query parameter (which seems to be for another kind of tokens - not the tokens generated using the IAM API key) and I receive an "ERCD-INVLDTKN" error when trying to send a request. It seems there is no longer a way to generate a token for the `token` parameter required by this library.

**Comment by catcher-in-the-try** [comment]
By trial and error I found a way to generate username/password in the IBM console, but still don't know how I did it. Just created a new service.

**Comment by germanattanasio** [comment]
We are in the middle of an update to make this library work with IAM tokens.

**Comment by germanattanasio** [comment]
We updated the library with support for IAM, you will have to get a token and use the `access_token` if is an IAM instance. `token` will remain there for CF instances.
