### ISSUE TITLE
Use TTS with other than default instance

### ISSUE THREAD

**Issue by magnusltmn** [watson-developer-cloud/speech-javascript-sdk#80]
I tried to use the "text-to-speech" service from "watson-speech" with a TTS service from an instance in Frankfurt, Germany. After getting a correct token, I am executing the following code:

```js
synthesize({
  text:  message,
  token: ttsToken,
  voice: "en-US_LisaVoice",
  autoPlay: true
});
```

The problem here is that the synthesize() is trying to establish a connection to "https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?" and not to "https://stream**-fra**.watsonplatform.net/text-to-speech/api/v1/synthesize?". I tried to give the synthesize() a new audio with the Frankfurt link via "options.element".

The problem here is that no matter what I am writing in the `options.element`, the `synthesize()` method always overwrites the url/ src with the default `stream.watsonplatform...` url.

So this part:
```js
var audio = options.element || new Audio();
  audio.crossOrigin = 'anonymous';
  audio.src = 'https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?' + qs.stringify(pick(options, QUERY_PARAMS_ALLOWED));
```

Should be changed into something like:

```js
var audio = options.element || new Audio();
if(options.element){
     audio.crossOrigin = 'anonymous';
     audio.src = 'https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?' + qs.stringify(pick(options, QUERY_PARAMS_ALLOWED));
}
```

**Comment by germanattanasio** [comment]
Hi @magnusltmn this was fixed in https://github.com/watson-developer-cloud/speech-javascript-sdk/releases/tag/v0.35.0

**Comment by germanattanasio** [comment]
Now you can specify the URL as part of the `synthesize()` method 
```js
synthesize({
  text:  message,
  url: 'https://stream-fra.watsonplatform.net/text-to-speech/api',
  token: ttsToken,
  voice: "en-US_LisaVoice",
  autoPlay: true
});
```

**Comment by daphoenix** [comment]
Thanks for the prompt fix.
