### ISSUE TITLE
how to add assistant to example

### ISSUE THREAD

**Issue by hoyeunglee** [watson-developer-cloud/speech-javascript-sdk#86]
i add
```
from watson_developer_cloud import AssistantV1 as Assistant

@app.route('/api/assistant/token')
def getAssToken():
	authorization = Authorization(username=ASS_USERNAME, password=ASS_PASSWORD)
	return authorization.get_token(url=Assistant.default_url)
```

where can find assistant in directory?
```
examples\static\bower_components
```

**Comment by dpopp07** [comment]
Hi @hoyeunglee 
This repository is for speech services only. If you are trying to integrate Assistant also, you will need to use the [watson-developer-cloud](https://github.com/watson-developer-cloud/node-sdk) package, which it looks like you are already using to import Assistant into your server code.

However, the Bower components do not automatically include that dependency. You will need to update [examples/bower.json](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/bower.json) to include Assistant as a dependency for your browser-side code.

Let me know if you have any more questions.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it.
