### ISSUE TITLE
Pull request #82 ships code incompatible with some browsers

### ISSUE THREAD

**Issue by vpicone** [watson-developer-cloud/speech-javascript-sdk#88]
#82 uses template literals which aren't supported in ie 11. Regular string concatenation should be used or the code should be compiled to es5 before being shipped. 

This was discovered when my build script failed due to es6 code being discovered in one of my deps.

**Comment by vpicone** [comment]
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/watson-speech/speech-to-text/get-models.js:57

Read more here: http://bit.ly/2tRViJ9
```

**Comment by dpopp07** [comment]
Thanks for letting us know, I opened #89 to resolve.
