### ISSUE TITLE
Use audio_url as the audio source instead of a stream

### ISSUE THREAD

**Issue by VadimGut** [watson-developer-cloud/speech-javascript-sdk#91]
It seems like when transferring **audio_url** with my job request

```js
	const createJobParams = {
		'callback_url': 'https://...',
		'user_token': 'foobar',
		'audio_url': 'https://....mp3',
		'content_type': 'audio/mpeg',
		objectMode: true,
		speaker_labels: true,
		timestamps: true
	};
        speechToText.createJob(createJobParams, ...
```

I am receiving the error 
`Error: Missing required parameters: audio`
which seems like it is not recognising the audio_url param

**Comment by germanattanasio** [comment]
Dustin can you look at this?

**Comment by dpopp07** [comment]
Hi @VadimGut 
First of all - are you using the `watson-speech` package or `watson-developer-cloud` ? This repo is for `watson-speech` which does not have an API for `createJob`. I think it would be more appropriate to post this issue in [the Node SDK repository](https://github.com/watson-developer-cloud/node-sdk/issues).

Second - I am not sure the service or SDKs are meant to accept an `audio_url` parameter for Speech to Text. I can't find it documented anywhere. I think it may be required for you to load the audio in your application and pass it to the SDK using the `audio` paremeter.

@germanattanasio Do you know if we should be handling `audio_url` as a parameter? I don't see it documented, even for curl.

**Comment by germanattanasio** [comment]
It doesn't look like `audio_url` is a supported.
See the documentation: https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#create-job

**Comment by VadimGut** [comment]
I have an email from **Daniel Bolanos** saying quote 

> Note however that this is done through the use of the "audio_url" parameter, which is a hidden feature at the moment. In general, any file based recognition where the file is longer than a few minutes it should be done using this API, since it is more robust ...
