### ISSUE TITLE
Synthesize method of /text-to-speech/synthesize.js also does not accept access_token

### ISSUE THREAD

**Issue by NobuyukiMonna** [watson-developer-cloud/speech-javascript-sdk#94]
Tieket # 92 asked QUERY_PARAMS_ALLOWED to add 'access_token'

  speech-javascript-sdk / text-to-speech / synthesize.js
Because it has not been added to QUERY_PARAMS_ALLOWED, this is a state that does not work.

Also, when adding 'access_token' to QUERY_PARAMS_ALLOWED
https://github.com/watson-developer-cloud/speech-javascript-sdk/commit/3042c9adfc71f4b5e89a34908a6ce9400c64f324#diff-117eb642eb2c4d69902800c2880fc9cd
`|| key === 'access_token'` has been deleted, you should add this.

I'd appreciate your correspondence

- [x] Steps to reproduce
- Same as # 92
- [x] Expected behavior
- Same as # 92
- [x] Actual behavior
- Same as # 92
- [x] Browser version (s)
- Firefox 63.0.1 (64 bit)
- [x] SDK version
- v 0.35.2

**Comment by germanattanasio** [comment]
@dpopp07 can you look at this please?

**Comment by NobuyukiMonna** [comment]
Hi @dpopp07

I am sorry even if the response is delayed
Also, thank you for your prompt response.

As for || key === 'access_token' being removed - This is my misunderstanding. I misunderstood that token and access_token must be the same implementation, but I confirmed that there is no particular problem. Thank you very much.
