### ISSUE TITLE
Since Synthesize method always adds watson-token parameter, it becomes 401 response when access_token is specified.

### ISSUE THREAD

**Issue by NobuyukiMonna** [watson-developer-cloud/speech-javascript-sdk#96]
I am sorry I have issued Issue many times due to my lack of confirmation
The access_token parameter of synthesize.js is still not working.
Because it is a different problem, I have voted for another Issue.

The cause is Synthesize.js L: 49, 59
```
   options ['watson-token'] = options.token;
   delete options.token;
```
By having unconditionally setting the 'watson-token' attribute
Authentication failed and it became an HTTP status code 401 (unauthorized).

speech-to-text / recognize-stream.js Like line 137
Could you add a check for the existence of "options.token"?
(I think that checking that 'watson-token' does not exist is unnecessary ..)

I confirmed it by deleting the watson-token parameter with "Edit and Resend" in "fierfox" Developper Tools and resending it
By deleting the watson - token parameter, HTTP status code 200 has been reached.

- [x] Steps to reproduce
- Same as #92 or #94
- [x] Expected behavior
- Same as #92 or #94
- [x] Actual behavior
- Same as #92 or #94
- [x] Browser version (s)
- Firefox 63.0.1 (64 bit)
- [x] SDK version
- v 0.35.2

**Comment by dpopp07** [comment]
@NobuyukiMonna thanks for opening another issue - you are correct, that code shouldn't be only looking for `watson-token`. I will have this fixed shortly

**Comment by NobuyukiMonna** [comment]
@dpopp07 Thank you for responding very quickly.
With this correspondence TTS can now operate with Iam authentication
It was very helpful
