### ISSUE TITLE
Use of 'customization_id' is deprecated - use 'language_customization_id' instead

### ISSUE THREAD

**Issue by ptuton** [watson-developer-cloud/speech-javascript-sdk#98]
As per the API [reference](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/), the use of 'customization_id' is deprecated, replaced with 'language_customization_id'.

SDK version: 0.36.0.

**Comment by dpopp07** [comment]
Hi @ptuton 

This SDK now uses the custom stream found in the [Watson Node SDK](https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/recognize-stream.ts#L115), which supports `language_customization_id`.
